<?php

/**
 * Description of SeccionesController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 16-Sep-2014
 *
 */
class SeccionesController extends ControllerProject {

    protected $controller = "Secciones";

}